OPPORTUNITIES_BY_ID = {'actuarial_and_data_science_society_adss': {'faculty': 'CPSC',
                                             'link': 'https://adssucalgary.ca/',
                                             'name': 'Actuarial & Data Science Society (ADSS)',
                                             'pre_reqs': '',
                                             'season': 'Year-Round',
                                             'skills': ['Data science',
                                                        'analytics',
                                                        'Python/R',
                                                        'professional development'],
                                             'time_per_week': '1hr-3hr',
                                             'type': 'Club'},
 'artificial_intelligence_club_aic': {'faculty': 'CPSC',
                                      'link': 'https://www.vision-research.ca/aic',
                                      'name': 'Artificial Intelligence Club (AIC)',
                                      'pre_reqs': '',
                                      'season': 'Fall and Winter Semesters',
                                      'skills': ['Machine learning',
                                                 'neural networks',
                                                 'Python',
                                                 'AI research',
                                                 'project development'],
                                      'time_per_week': '2hr-5hr',
                                      'type': 'Research'},
 'baja': {'faculty': 'ENG',
          'link': 'https://ucalgbaja.ca/',
          'name': 'Baja',
          'pre_reqs': 'helpful, but not mandatory',
          'season': 'Year-Round',
          'skills': ['Teamwork',
                     'Communication',
                     'Planning',
                     'Documentation',
                     'Problem Solving',
                     'Git',
                     'Testing',
                     'Python',
                     'C/C++',
                     'Embedded',
                     'SQL',
                     'Data Analysis',
                     'PCB Design',
                     'CAD',
                     'Leadership'],
          'time_per_week': '6hr-10hr',
          'type': 'Design Team'},
 'bmerit': {'faculty': 'ENG',
            'link': 'https://bmerit.vercel.app/',
            'name': 'BMERIT',
            'pre_reqs': 'helpful, but not mandatory',
            'season': 'Year-Round',
            'skills': ['Teamwork',
                       'Communication',
                       'Planning',
                       'Documentation',
                       'Problem Solving',
                       'Git',
                       'Testing',
                       'Python',
                       'C/C++',
                       'Embedded',
                       'SQL',
                       'Data Analysis',
                       'PCB Design',
                       'CAD',
                       'Leadership'],
            'time_per_week': '6hr-10hr',
            'type': 'Design Team'},
 'calgary_racing': {'faculty': 'ENG',
                    'link': 'https://ucalgaryracing.ca/',
                    'name': 'Calgary Racing',
                    'pre_reqs': 'helpful, but not mandatory',
                    'season': 'Year-Round',
                    'skills': ['Teamwork',
                               'Communication',
                               'Planning',
                               'Documentation',
                               'Problem Solving',
                               'Git',
                               'Testing',
                               'Python',
                               'C/C++',
                               'Embedded',
                               'SQL',
                               'Data Analysis',
                               'PCB Design',
                               'CAD',
                               'Leadership'],
                    'time_per_week': '6hr-10hr',
                    'type': 'Design Team'},
 'calgarytospace': {'faculty': 'ENG',
                    'link': 'https://www.calgarytospace.ca/',
                    'name': 'CalgaryToSpace',
                    'pre_reqs': 'helpful, but not mandatory',
                    'season': 'Year-Round',
                    'skills': ['Teamwork',
                               'Communication',
                               'Planning',
                               'Documentation',
                               'Problem Solving',
                               'Git',
                               'Testing',
                               'Python',
                               'C/C++',
                               'Embedded',
                               'SQL',
                               'Data Analysis',
                               'PCB Design',
                               'CAD',
                               'Leadership'],
                    'time_per_week': '6hr-10hr',
                    'type': 'Design Team'},
 'competitive_programming_club': {'faculty': 'CPSC',
                                  'link': 'https://cpc.cpsc.ucalgary.ca/',
                                  'name': 'Competitive Programming Club',
                                  'pre_reqs': 'helpful, but not mandatory',
                                  'season': 'Fall and Winter Semesters',
                                  'skills': ['Algorithms',
                                             'data structures',
                                             'problem solving',
                                             'Python/C++ coding',
                                             'interview prep'],
                                  'time_per_week': '1hr-3hr',
                                  'type': 'Club'},
 'computer_science_undergraduate_society': {'faculty': 'CPSC',
                                            'link': 'https://csus.club/',
                                            'name': 'Computer Science Undergraduate Society',
                                            'pre_reqs': '',
                                            'season': 'Year-Round',
                                            'skills': ['Networking',
                                                       'hackathon participation',
                                                       'teamwork',
                                                       'software project collaboration',
                                                       'career preparation'],
                                            'time_per_week': '1hr-3hr',
                                            'type': 'Club'},
 'cybersec_ucalgary_cybersecurity_club': {'faculty': 'CPSC',
                                          'link': 'https://cybersec-ucalgary.club/',
                                          'name': 'CYBERSEC (UCalgary CyberSecurity Club)',
                                          'pre_reqs': '',
                                          'season': 'Year-Round',
                                          'skills': ['Cybersecurity', 'CTFs', 'networking', 'security tools'],
                                          'time_per_week': '1hr-4hr',
                                          'type': 'Club'},
 'data_science_and_machine_learning_club': {'faculty': 'CPSC',
                                            'link': 'https://www.dsmlcucalgary.ca/',
                                            'name': 'Data Science and Machine Learning Club',
                                            'pre_reqs': '',
                                            'season': 'Year-Round',
                                            'skills': ['Python',
                                                       'machine learning',
                                                       'SQL',
                                                       'data analysis',
                                                       'Power BI',
                                                       'AI concepts'],
                                            'time_per_week': '2hr-4hr',
                                            'type': 'Club'},
 'developer_student_club_dsc_ucalgary': {'faculty': 'CPSC',
                                         'link': 'https://dsc-uofc-website.herokuapp.com/',
                                         'name': 'Developer Student Club (DSC) UCalgary',
                                         'pre_reqs': '',
                                         'season': 'Year-Round',
                                         'skills': ['App dev', 'web dev', 'cloud', 'workshops', 'networking'],
                                         'time_per_week': '1hr-4hr',
                                         'type': 'Club'},
 'game_design_club_gdc': {'faculty': 'CPSC',
                          'link': 'https://uofcgamedesignclub.itch.io/',
                          'name': 'Game Design Club (GDC)',
                          'pre_reqs': '',
                          'season': 'Year-Round',
                          'skills': ['Game development', 'Unity', 'C#', 'teamwork', 'software design'],
                          'time_per_week': '1hr-3hr',
                          'type': 'Club'},
 'gnctr_toboggan': {'faculty': 'ENG',
                    'link': 'https://gnctruofc.wordpress.com/',
                    'name': 'GNCTR (Toboggan)',
                    'pre_reqs': 'helpful, but not mandatory',
                    'season': 'Year-Round',
                    'skills': ['Teamwork',
                               'Communication',
                               'Planning',
                               'Documentation',
                               'Problem Solving',
                               'Git',
                               'Testing',
                               'Python',
                               'C/C++',
                               'Embedded',
                               'SQL',
                               'Data Analysis',
                               'PCB Design',
                               'CAD',
                               'Leadership'],
                    'time_per_week': '6hr-10hr',
                    'type': 'Design Team'},
 'gobabygo_ucalgary': {'faculty': 'ENG',
                       'link': 'https://schulich.ucalgary.ca/current-students/undergraduate/student-life/clubs-teams',
                       'name': 'GoBabyGo UCalgary',
                       'pre_reqs': '',
                       'season': 'Year-Round',
                       'skills': ['Assistive tech', 'embedded/software', 'hardware integration'],
                       'time_per_week': '1hr-4hr',
                       'type': 'Club'},
 'hack4health_ucalgary': {'faculty': 'CPSC',
                          'link': 'https://www.hack4health.ca/',
                          'name': 'Hack4Health UCalgary',
                          'pre_reqs': '',
                          'season': 'Event-Based',
                          'skills': ['Hackathon building', 'teamwork', 'rapid prototyping'],
                          'time_per_week': '8hr-24hr',
                          'type': 'Event/Community'},
 'ieee_ucalgary_student_branch': {'faculty': 'ENG',
                                  'link': 'https://ieee-ucalgary.ca/',
                                  'name': 'IEEE UCalgary Student Branch',
                                  'pre_reqs': '',
                                  'season': 'Year-Round',
                                  'skills': ['Tech talks', 'networking', 'embedded/IoT', 'workshops'],
                                  'time_per_week': '1hr-3hr',
                                  'type': 'Club'},
 'igem_calgary_dry_lab_software': {'faculty': 'CPSC',
                                   'link': 'https://2025.igem.wiki/ucalgary/index.html',
                                   'name': 'iGEM Calgary (Dry Lab + Software)',
                                   'pre_reqs': '',
                                   'season': 'Summer + Year-Round',
                                   'skills': ['Modeling', 'data analysis', 'software tools', 'teamwork'],
                                   'time_per_week': '2hr-8hr',
                                   'type': 'Research'},
 'information_security_club': {'faculty': 'CPSC',
                               'link': 'https://www.linkedin.com/company/cybersec-ucalgary/',
                               'name': 'Information Security Club',
                               'pre_reqs': '',
                               'season': 'Year-Round',
                               'skills': ['Cybersecurity', 'ethical hacking', 'Linux', 'networking', 'security tools'],
                               'time_per_week': '1hr-3hr',
                               'type': 'Club'},
 'mind_mechatronics_innovation_design': {'faculty': 'ENG',
                                         'link': 'https://www.minducalgary.com/',
                                         'name': 'MIND (Mechatronics Innovation Design)',
                                         'pre_reqs': '',
                                         'season': 'Year-Round',
                                         'skills': ['Robotics', 'embedded systems', 'prototyping', 'teamwork'],
                                         'time_per_week': '2hr-6hr',
                                         'type': 'Club'},
 'minds_in_motion': {'faculty': 'ENG',
                     'link': 'https://www.ucalgary.ca/active-living/programs/youth-programs/robotics-community-programs',
                     'name': 'Minds in Motion',
                     'pre_reqs': '',
                     'season': 'Year-Round',
                     'skills': ['Robotics mentoring', 'STEM outreach', 'leadership'],
                     'time_per_week': '1hr-4hr',
                     'type': 'Program'},
 'project90': {'faculty': 'ENG',
               'link': 'https://project90.ca/',
               'name': 'Project90',
               'pre_reqs': 'helpful, but not mandatory',
               'season': 'Year-Round',
               'skills': ['Teamwork',
                          'Communication',
                          'Planning',
                          'Documentation',
                          'Problem Solving',
                          'Git',
                          'Testing',
                          'Python',
                          'C/C++',
                          'Embedded',
                          'SQL',
                          'Data Analysis',
                          'PCB Design',
                          'CAD',
                          'Leadership'],
               'time_per_week': '6hr-10hr',
               'type': 'Club'},
 'revolt_ev': {'faculty': 'ENG',
               'link': 'https://schulich.ucalgary.ca/current-students/undergraduate/student-life/clubs-teams',
               'name': 'ReVOLT EV',
               'pre_reqs': '',
               'season': 'Year-Round',
               'skills': ['EV projects', 'embedded/software', 'teamwork', 'Git'],
               'time_per_week': '2hr-6hr',
               'type': 'Club'},
 'schulich_community_robotics_program_scrp': {'faculty': 'ENG',
                                              'link': 'https://www.ucalgary.ca/active-living/programs/youth-programs/robotics-community-programs',
                                              'name': 'Schulich Community Robotics Program (SCRP)',
                                              'pre_reqs': '',
                                              'season': 'Year-Round',
                                              'skills': ['Robotics outreach', 'mentoring', 'programming basics'],
                                              'time_per_week': '1hr-4hr',
                                              'type': 'Program'},
 'schulich_ignite': {'faculty': 'ENG',
                     'link': 'https://schulichignite.com/',
                     'name': 'Schulich Ignite',
                     'pre_reqs': '',
                     'season': 'Fall and Winter Semesters',
                     'skills': ['Programming mentorship', 'workshops', 'project building', 'teamwork'],
                     'time_per_week': '1hr-3hr',
                     'type': 'Club'},
 'soar': {'faculty': 'ENG',
          'link': 'https://www.soar-rockets.ca/',
          'name': 'SOAR',
          'pre_reqs': 'helpful, but not mandatory',
          'season': 'Year-Round',
          'skills': ['Teamwork',
                     'Communication',
                     'Planning',
                     'Documentation',
                     'Problem Solving',
                     'Git',
                     'Testing',
                     'Python',
                     'C/C++',
                     'Embedded',
                     'SQL',
                     'Data Analysis',
                     'PCB Design',
                     'CAD',
                     'Leadership'],
          'time_per_week': '6hr-10hr',
          'type': 'Design Team'},
 'society_of_asian_scientists_and_engineers_sase': {'faculty': 'CPSC',
                                                    'link': 'https://www.saseucalgary.com/',
                                                    'name': 'Society of Asian Scientists & Engineers (SASE)',
                                                    'pre_reqs': '',
                                                    'season': 'Year-Round',
                                                    'skills': ['Professional development',
                                                               'networking',
                                                               'tech career skills'],
                                                    'time_per_week': '1hr-3hr',
                                                    'type': 'Club'},
 'solar_car_team': {'faculty': 'ENG',
                    'link': 'https://calgarysolarcar.ca/',
                    'name': 'Solar Car Team',
                    'pre_reqs': 'helpful, but not mandatory',
                    'season': 'Year-Round',
                    'skills': ['Teamwork',
                               'Communication',
                               'Planning',
                               'Documentation',
                               'Problem Solving',
                               'Git',
                               'Testing',
                               'Python',
                               'C/C++',
                               'Embedded',
                               'SQL',
                               'Data Analysis',
                               'PCB Design',
                               'CAD',
                               'Leadership'],
                    'time_per_week': '6hr-10hr',
                    'type': 'Design Team'},
 'space_rover_team': {'faculty': 'ENG',
                      'link': 'https://ucalgaryrover.weebly.com/',
                      'name': 'Space Rover Team',
                      'pre_reqs': 'helpful, but not mandatory',
                      'season': 'Year-Round',
                      'skills': ['Teamwork',
                                 'Communication',
                                 'Planning',
                                 'Documentation',
                                 'Problem Solving',
                                 'Git',
                                 'Testing',
                                 'Python',
                                 'C/C++',
                                 'Embedded',
                                 'SQL',
                                 'Data Analysis',
                                 'PCB Design',
                                 'CAD',
                                 'Leadership'],
                      'time_per_week': '6hr-10hr',
                      'type': 'Design Team'},
 'stem_fellowship_ucalgary_branch': {'faculty': 'CPSC',
                                     'link': 'https://live.stemfellowship.org/university-branches/university-of-calgary-branch/',
                                     'name': 'STEM Fellowship UCalgary Branch',
                                     'pre_reqs': '',
                                     'season': 'Year-Round',
                                     'skills': ['Workshops', 'computational thinking', 'data/AI', 'leadership'],
                                     'time_per_week': '1hr-3hr',
                                     'type': 'Club'},
 'team_zeus': {'faculty': 'ENG',
               'link': 'https://www.teamzeus.ca/',
               'name': 'Team Zeus',
               'pre_reqs': 'helpful, but not mandatory',
               'season': 'Year-Round',
               'skills': ['Teamwork',
                          'Communication',
                          'Planning',
                          'Documentation',
                          'Problem Solving',
                          'Git',
                          'Testing',
                          'Python',
                          'C/C++',
                          'Embedded',
                          'SQL',
                          'Data Analysis',
                          'PCB Design',
                          'CAD',
                          'Leadership'],
               'time_per_week': '6hr-10hr',
               'type': 'Design Team'},
 'tech_start_ucalgary': {'faculty': 'CPSC',
                         'link': 'https://techstartucalgary.com/',
                         'name': 'Tech Start UCalgary',
                         'pre_reqs': '',
                         'season': 'Year-Round',
                         'skills': ['Software dev', 'product building', 'teamwork', 'Git', 'agile'],
                         'time_per_week': '2hr-6hr',
                         'type': 'Club'},
 'ucalgary_bioinformatics_club': {'faculty': 'CPSC',
                                  'link': 'https://linktr.ee/ucalgarybioinformatics',
                                  'name': 'UCalgary Bioinformatics Club',
                                  'pre_reqs': '',
                                  'season': 'Year-Round',
                                  'skills': ['Bioinformatics', 'Python/R', 'data analysis', 'research skills'],
                                  'time_per_week': '1hr-3hr',
                                  'type': 'Club'},
 'ucalgary_blockchain_society': {'faculty': 'CPSC',
                                 'link': 'https://suuofc.campuslabs.ca/engage/organization/ucalgary-blockchain-society',
                                 'name': 'UCalgary Blockchain Society',
                                 'pre_reqs': '',
                                 'season': 'Year-Round',
                                 'skills': ['Blockchain fundamentals',
                                            'smart contracts',
                                            'dev workshops',
                                            'networking'],
                                 'time_per_week': '1hr-3hr',
                                 'type': 'Club'},
 'ucalgary_design_league': {'faculty': 'ENG',
                            'link': 'https://ucdesignleague.square.site/',
                            'name': 'uCalgary Design League',
                            'pre_reqs': '',
                            'season': 'Year-Round',
                            'skills': ['CAD', 'design thinking', 'prototyping', 'designathons'],
                            'time_per_week': '1hr-4hr',
                            'type': 'Club'},
 'university_of_calgary_robotics_club': {'faculty': 'ENG',
                                         'link': 'https://www.ucalgary.ca/active-living/programs/youth-programs/robotics-community-programs',
                                         'name': 'University of Calgary Robotics Club',
                                         'pre_reqs': '',
                                         'season': 'Year-Round',
                                         'skills': ['Robotics', 'programming', 'building', 'teamwork'],
                                         'time_per_week': '2hr-6hr',
                                         'type': 'Club'},
 'unmanned_aerial_vehicles_suav': {'faculty': 'ENG',
                                   'link': 'https://calgaryuav.com/',
                                   'name': 'Unmanned Aerial Vehicles (SUAV)',
                                   'pre_reqs': 'helpful, but not mandatory',
                                   'season': 'Year-Round',
                                   'skills': ['Teamwork',
                                              'Communication',
                                              'Planning',
                                              'Documentation',
                                              'Problem Solving',
                                              'Git',
                                              'Testing',
                                              'Python',
                                              'C/C++',
                                              'Embedded',
                                              'SQL',
                                              'Data Analysis',
                                              'PCB Design',
                                              'CAD',
                                              'Leadership'],
                                   'time_per_week': '6hr-10hr',
                                   'type': 'Design Team'},
 'uofc_fintech': {'faculty': 'CPSC',
                  'link': 'https://suuofc.campuslabs.ca/engage/organization/fintechcalgary',
                  'name': 'UofC FinTech',
                  'pre_reqs': '',
                  'season': 'Year-Round',
                  'skills': ['Fintech projects', 'data analysis', 'Python', 'networking'],
                  'time_per_week': '1hr-3hr',
                  'type': 'Club'},
 'user_experience_design_club_uxdc': {'faculty': 'CPSC',
                                      'link': 'https://linktr.ee/uxdc.uofc',
                                      'name': 'User Experience Design Club (UXDC)',
                                      'pre_reqs': '',
                                      'season': 'Year-Round',
                                      'skills': ['UX/UI', 'product design', 'prototyping', 'user research'],
                                      'time_per_week': '1hr-3hr',
                                      'type': 'Club'},
 'waybionic': {'faculty': 'ENG',
               'link': 'https://www.waybionic.com/',
               'name': 'WayBionic',
               'pre_reqs': 'helpful, but not mandatory',
               'season': 'Year-Round',
               'skills': ['Teamwork',
                          'Communication',
                          'Planning',
                          'Documentation',
                          'Problem Solving',
                          'Git',
                          'Testing',
                          'Python',
                          'C/C++',
                          'Embedded',
                          'SQL',
                          'Data Analysis',
                          'PCB Design',
                          'CAD',
                          'Leadership'],
               'time_per_week': '6hr-10hr',
               'type': 'Design Team'},
 'wics_women_in_computer_science': {'faculty': 'CPSC',
                                    'link': 'https://www.instagram.com/wics.uofc/',
                                    'name': 'WiCS (Women in Computer Science)',
                                    'pre_reqs': '',
                                    'season': 'Year-Round',
                                    'skills': ['Networking', 'mentorship', 'career talks', 'community'],
                                    'time_per_week': '1hr-3hr',
                                    'type': 'Club'},
 'wicys_ucalgary': {'faculty': 'CPSC',
                    'link': 'https://www.instagram.com/wicys.uofc/',
                    'name': 'WiCyS @ UCalgary',
                    'pre_reqs': '',
                    'season': 'Year-Round',
                    'skills': ['Cybersecurity', 'networking', 'career development', 'workshops'],
                    'time_per_week': '1hr-3hr',
                    'type': 'Club'},
 'women_in_science_and_engineering_wise': {'faculty': 'ENG',
                                           'link': 'https://www.uofcwise.com/',
                                           'name': 'Women in Science and Engineering (WISE)',
                                           'pre_reqs': '',
                                           'season': 'Year-Round',
                                           'skills': ['Mentorship', 'professional development', 'STEM community'],
                                           'time_per_week': '1hr-3hr',
                                           'type': 'Club'}}

# Same data as a list (useful for iteration / filtering)
OPPORTUNITIES_LIST = [{'faculty': 'ENG',
  'id': 'soar',
  'link': 'https://www.soar-rockets.ca/',
  'name': 'SOAR',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Design Team'},
 {'faculty': 'ENG',
  'id': 'baja',
  'link': 'https://ucalgbaja.ca/',
  'name': 'Baja',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Design Team'},
 {'faculty': 'ENG',
  'id': 'bmerit',
  'link': 'https://bmerit.vercel.app/',
  'name': 'BMERIT',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Design Team'},
 {'faculty': 'ENG',
  'id': 'calgarytospace',
  'link': 'https://www.calgarytospace.ca/',
  'name': 'CalgaryToSpace',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Design Team'},
 {'faculty': 'ENG',
  'id': 'calgary_racing',
  'link': 'https://ucalgaryracing.ca/',
  'name': 'Calgary Racing',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Design Team'},
 {'faculty': 'ENG',
  'id': 'gnctr_toboggan',
  'link': 'https://gnctruofc.wordpress.com/',
  'name': 'GNCTR (Toboggan)',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Design Team'},
 {'faculty': 'ENG',
  'id': 'space_rover_team',
  'link': 'https://ucalgaryrover.weebly.com/',
  'name': 'Space Rover Team',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Design Team'},
 {'faculty': 'ENG',
  'id': 'unmanned_aerial_vehicles_suav',
  'link': 'https://calgaryuav.com/',
  'name': 'Unmanned Aerial Vehicles (SUAV)',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Design Team'},
 {'faculty': 'ENG',
  'id': 'team_zeus',
  'link': 'https://www.teamzeus.ca/',
  'name': 'Team Zeus',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Design Team'},
 {'faculty': 'ENG',
  'id': 'solar_car_team',
  'link': 'https://calgarysolarcar.ca/',
  'name': 'Solar Car Team',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Design Team'},
 {'faculty': 'ENG',
  'id': 'waybionic',
  'link': 'https://www.waybionic.com/',
  'name': 'WayBionic',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Design Team'},
 {'faculty': 'ENG',
  'id': 'project90',
  'link': 'https://project90.ca/',
  'name': 'Project90',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Year-Round',
  'skills': ['Teamwork',
             'Communication',
             'Planning',
             'Documentation',
             'Problem Solving',
             'Git',
             'Testing',
             'Python',
             'C/C++',
             'Embedded',
             'SQL',
             'Data Analysis',
             'PCB Design',
             'CAD',
             'Leadership'],
  'time_per_week': '6hr-10hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'computer_science_undergraduate_society',
  'link': 'https://csus.club/',
  'name': 'Computer Science Undergraduate Society',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Networking',
             'hackathon participation',
             'teamwork',
             'software project collaboration',
             'career preparation'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'competitive_programming_club',
  'link': 'https://cpc.cpsc.ucalgary.ca/',
  'name': 'Competitive Programming Club',
  'pre_reqs': 'helpful, but not mandatory',
  'season': 'Fall and Winter Semesters',
  'skills': ['Algorithms', 'data structures', 'problem solving', 'Python/C++ coding', 'interview prep'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'data_science_and_machine_learning_club',
  'link': 'https://www.dsmlcucalgary.ca/',
  'name': 'Data Science and Machine Learning Club',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Python', 'machine learning', 'SQL', 'data analysis', 'Power BI', 'AI concepts'],
  'time_per_week': '2hr-4hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'artificial_intelligence_club_aic',
  'link': 'https://www.vision-research.ca/aic',
  'name': 'Artificial Intelligence Club (AIC)',
  'pre_reqs': '',
  'season': 'Fall and Winter Semesters',
  'skills': ['Machine learning', 'neural networks', 'Python', 'AI research', 'project development'],
  'time_per_week': '2hr-5hr',
  'type': 'Research'},
 {'faculty': 'CPSC',
  'id': 'information_security_club',
  'link': 'https://www.linkedin.com/company/cybersec-ucalgary/',
  'name': 'Information Security Club',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Cybersecurity', 'ethical hacking', 'Linux', 'networking', 'security tools'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'game_design_club_gdc',
  'link': 'https://uofcgamedesignclub.itch.io/',
  'name': 'Game Design Club (GDC)',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Game development', 'Unity', 'C#', 'teamwork', 'software design'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'tech_start_ucalgary',
  'link': 'https://techstartucalgary.com/',
  'name': 'Tech Start UCalgary',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Software dev', 'product building', 'teamwork', 'Git', 'agile'],
  'time_per_week': '2hr-6hr',
  'type': 'Club'},
 {'faculty': 'ENG',
  'id': 'schulich_ignite',
  'link': 'https://schulichignite.com/',
  'name': 'Schulich Ignite',
  'pre_reqs': '',
  'season': 'Fall and Winter Semesters',
  'skills': ['Programming mentorship', 'workshops', 'project building', 'teamwork'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'developer_student_club_dsc_ucalgary',
  'link': 'https://dsc-uofc-website.herokuapp.com/',
  'name': 'Developer Student Club (DSC) UCalgary',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['App dev', 'web dev', 'cloud', 'workshops', 'networking'],
  'time_per_week': '1hr-4hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'wics_women_in_computer_science',
  'link': 'https://www.instagram.com/wics.uofc/',
  'name': 'WiCS (Women in Computer Science)',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Networking', 'mentorship', 'career talks', 'community'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'wicys_ucalgary',
  'link': 'https://www.instagram.com/wicys.uofc/',
  'name': 'WiCyS @ UCalgary',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Cybersecurity', 'networking', 'career development', 'workshops'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'cybersec_ucalgary_cybersecurity_club',
  'link': 'https://cybersec-ucalgary.club/',
  'name': 'CYBERSEC (UCalgary CyberSecurity Club)',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Cybersecurity', 'CTFs', 'networking', 'security tools'],
  'time_per_week': '1hr-4hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'uofc_fintech',
  'link': 'https://suuofc.campuslabs.ca/engage/organization/fintechcalgary',
  'name': 'UofC FinTech',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Fintech projects', 'data analysis', 'Python', 'networking'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'ucalgary_blockchain_society',
  'link': 'https://suuofc.campuslabs.ca/engage/organization/ucalgary-blockchain-society',
  'name': 'UCalgary Blockchain Society',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Blockchain fundamentals', 'smart contracts', 'dev workshops', 'networking'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'user_experience_design_club_uxdc',
  'link': 'https://linktr.ee/uxdc.uofc',
  'name': 'User Experience Design Club (UXDC)',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['UX/UI', 'product design', 'prototyping', 'user research'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'ENG',
  'id': 'ucalgary_design_league',
  'link': 'https://ucdesignleague.square.site/',
  'name': 'uCalgary Design League',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['CAD', 'design thinking', 'prototyping', 'designathons'],
  'time_per_week': '1hr-4hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'stem_fellowship_ucalgary_branch',
  'link': 'https://live.stemfellowship.org/university-branches/university-of-calgary-branch/',
  'name': 'STEM Fellowship UCalgary Branch',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Workshops', 'computational thinking', 'data/AI', 'leadership'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'actuarial_and_data_science_society_adss',
  'link': 'https://adssucalgary.ca/',
  'name': 'Actuarial & Data Science Society (ADSS)',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Data science', 'analytics', 'Python/R', 'professional development'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'society_of_asian_scientists_and_engineers_sase',
  'link': 'https://www.saseucalgary.com/',
  'name': 'Society of Asian Scientists & Engineers (SASE)',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Professional development', 'networking', 'tech career skills'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'ENG',
  'id': 'women_in_science_and_engineering_wise',
  'link': 'https://www.uofcwise.com/',
  'name': 'Women in Science and Engineering (WISE)',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Mentorship', 'professional development', 'STEM community'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'ENG',
  'id': 'ieee_ucalgary_student_branch',
  'link': 'https://ieee-ucalgary.ca/',
  'name': 'IEEE UCalgary Student Branch',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Tech talks', 'networking', 'embedded/IoT', 'workshops'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'ENG',
  'id': 'revolt_ev',
  'link': 'https://schulich.ucalgary.ca/current-students/undergraduate/student-life/clubs-teams',
  'name': 'ReVOLT EV',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['EV projects', 'embedded/software', 'teamwork', 'Git'],
  'time_per_week': '2hr-6hr',
  'type': 'Club'},
 {'faculty': 'ENG',
  'id': 'mind_mechatronics_innovation_design',
  'link': 'https://www.minducalgary.com/',
  'name': 'MIND (Mechatronics Innovation Design)',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Robotics', 'embedded systems', 'prototyping', 'teamwork'],
  'time_per_week': '2hr-6hr',
  'type': 'Club'},
 {'faculty': 'ENG',
  'id': 'gobabygo_ucalgary',
  'link': 'https://schulich.ucalgary.ca/current-students/undergraduate/student-life/clubs-teams',
  'name': 'GoBabyGo UCalgary',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Assistive tech', 'embedded/software', 'hardware integration'],
  'time_per_week': '1hr-4hr',
  'type': 'Club'},
 {'faculty': 'ENG',
  'id': 'schulich_community_robotics_program_scrp',
  'link': 'https://www.ucalgary.ca/active-living/programs/youth-programs/robotics-community-programs',
  'name': 'Schulich Community Robotics Program (SCRP)',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Robotics outreach', 'mentoring', 'programming basics'],
  'time_per_week': '1hr-4hr',
  'type': 'Program'},
 {'faculty': 'ENG',
  'id': 'university_of_calgary_robotics_club',
  'link': 'https://www.ucalgary.ca/active-living/programs/youth-programs/robotics-community-programs',
  'name': 'University of Calgary Robotics Club',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Robotics', 'programming', 'building', 'teamwork'],
  'time_per_week': '2hr-6hr',
  'type': 'Club'},
 {'faculty': 'ENG',
  'id': 'minds_in_motion',
  'link': 'https://www.ucalgary.ca/active-living/programs/youth-programs/robotics-community-programs',
  'name': 'Minds in Motion',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Robotics mentoring', 'STEM outreach', 'leadership'],
  'time_per_week': '1hr-4hr',
  'type': 'Program'},
 {'faculty': 'CPSC',
  'id': 'ucalgary_bioinformatics_club',
  'link': 'https://linktr.ee/ucalgarybioinformatics',
  'name': 'UCalgary Bioinformatics Club',
  'pre_reqs': '',
  'season': 'Year-Round',
  'skills': ['Bioinformatics', 'Python/R', 'data analysis', 'research skills'],
  'time_per_week': '1hr-3hr',
  'type': 'Club'},
 {'faculty': 'CPSC',
  'id': 'igem_calgary_dry_lab_software',
  'link': 'https://2025.igem.wiki/ucalgary/index.html',
  'name': 'iGEM Calgary (Dry Lab + Software)',
  'pre_reqs': '',
  'season': 'Summer + Year-Round',
  'skills': ['Modeling', 'data analysis', 'software tools', 'teamwork'],
  'time_per_week': '2hr-8hr',
  'type': 'Research'},
 {'faculty': 'CPSC',
  'id': 'hack4health_ucalgary',
  'link': 'https://www.hack4health.ca/',
  'name': 'Hack4Health UCalgary',
  'pre_reqs': '',
  'season': 'Event-Based',
  'skills': ['Hackathon building', 'teamwork', 'rapid prototyping'],
  'time_per_week': '8hr-24hr',
  'type': 'Event/Community'}]
